name: Run Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Browser:'
        default: chrome
        required: true
        options:
          - chrome
          - firfox
          - safari
          - edge

jobs:
  build:
    name: Run Tests in - ${{ github.event.inputs.browser }}
    runs-on: macos-latest
    env:
      BROWSER: ${{ github.event.inputs.browser }}

    steps:
      
      # Check out the repository
      - uses: actions/checkout@v3

      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install your dependencies
      - run: npm ci
      - run: npx playwright install
      - run: npm run test:${{ env.BROWSER }}
      - name: Upload HTML report as artifact. To troubleshoot failures, extract .zip and double-click index.html.
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.BROWSER }}
          path: |
            playwright-report
